<?php echo $this->_getContainerSnippet(); ?>


<?php 
$refer = $_GET['refererd'];
 ?>
 <?php 
$write = Mage::getStoreConfig('redeal/redeal_group/section_two');
$isactive = Mage::getStoreConfig('redeal/redeal_group/redeal_select');
//echo $isactive ;


 ?>

<?php
if(Mage::app()->getFrontController()->getAction()->getFullActionName() == 'checkout_onepage_success') {  ?>
	<script>(function(i,s,o,g,r,a,m){i['RedealObject']=r;i[r]=i[r]||function(){
                 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
             })(window, document, 'script', window.location.protocol + '//widget.redeal.se/js/redeal.js', 'redeal');
    </script> 
<?php }
 
 
 if(Mage::app()->getFrontController()->getAction()->getFullActionName() != 'checkout_onepage_success') {
		 
		 // echo "<pre>";
		 // print_r($write);
		 // exit();
		 if($write == 2){
		 	$rdlurl = "//widget.redeal.se/js/redeal.js";
		 }else{
		 	$rdlurl = "//test-widget.redeal.se/js/redeal.js";
		 }
		 


?>

<?php if($isactive == 1) { ?>
<script>(function(i,s,o,g,r,a,m){i['RedealObject']=r;i[r]=i[r]||function(){
                 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
             })(window, document, 'script', window.location.protocol + '<?php echo $rdlurl?>', 'redeal');
    </script> 
 <?php } ?>

<?php }  ?>